baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.139.0"

[build]
  writeStats = true

[markup]
  [markup.highlight]
    noClasses = false

[params]
  mainSections = ["posts"]

[build.buildStats]
  enable = true

[minify]
  minifyOutput = true
