# Local backend configuration
backend:
  name: git-gateway
  local_backend: true

# These lines should match your site structure
media_folder: static/images/uploads
public_folder: /images/uploads

# Collections define the structure for content
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Last Modified", name: "lastmod", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Highlighted", name: "highlighted", widget: "boolean", default: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 